version: '3.9'
services: 
    db:
      image: mysql
      container_name: mysql_db
      ports:
        - 3306:3306
      environment:

      volumes:
        - challenge4:/var/lib/mysql/data

volumes:
  challenge4:
