version: '3.9'
services: 
    db:
      image: postgres
      container_name: pg_db
      ports:
        - 5432:5432
      restart: always
      environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_DB: test
      volumes:
        - challenge4:/var/lib/mysql

volumes:
  challenge4:
